server {
    listen 80;
    server_name search.top.secret;

    location = /top-secret-root-ca.crl {
        default_type application/pkix-crl;
        alias /etc/nginx/certs/top-secret-root-ca.crl;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name search.top.secret;

    ssl_certificate /etc/nginx/certs/search.top.secret.cert.pem;
    ssl_certificate_key /etc/nginx/certs/search.top.secret.key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:search_top_secret_tls:10m;
    ssl_session_timeout 1h;

    client_max_body_size 0;

    location = / {
        return 302 /search;
    }

    location / {
        proxy_pass http://connector-search:8090;
        proxy_http_version 1.1;
        proxy_read_timeout 3600s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 3600s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-User $http_x_forwarded_user;
        proxy_set_header X-Forwarded-Email $http_x_forwarded_email;
        proxy_set_header X-Forwarded-Name $http_x_forwarded_name;
    }
}
